// src/pages/Experience.tsx
import { motion } from 'motion/react';
import { useI18n } from '../lib/i18n';
import { experiences } from '../data';
import { Briefcase, Calendar } from 'lucide-react';

export default function Experience() {
  const { t, locale } = useI18n();

  return (
    <div className="space-y-16">
      <section className="max-w-3xl">
        <h2 className="text-4xl font-bold mb-4">{t('exp_title')}</h2>
        <p className="text-brand-oak text-lg">
          {locale === 'en' 
            ? "A journey through corporate finance, indie game development, and academic mentorship."
            : "穿梭于金融企业、独立游戏开发和学术辅导的职业历程。"}
        </p>
      </section>

      <div className="space-y-12 relative before:absolute before:left-0 before:top-0 before:w-px before:h-full before:bg-white/10 ml-4 pl-12">
        {experiences.map((exp, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ delay: index * 0.1 }}
            className="relative"
          >
            {/* Timeline Dot */}
            <div className="absolute -left-[53px] top-2 w-2 h-2 rounded-full bg-brand-copper shadow-[0_0_10px_rgba(181,132,90,0.5)]" />
            
            <div className="flex flex-col md:flex-row md:items-center justify-between mb-4">
              <div>
                <h3 className="text-2xl font-bold text-brand-parchment">{exp.company}</h3>
                <p className="text-brand-copper font-medium">{exp.role[locale]}</p>
              </div>
              <div className="flex items-center space-x-2 text-brand-oak/60 text-sm mt-2 md:mt-0">
                <Calendar size={14} />
                <span>{exp.period}</span>
              </div>
            </div>

            <ul className="space-y-3 mb-6">
              {exp.points[locale].map((point, i) => (
                <li key={i} className="text-brand-oak/90 flex items-start space-x-3">
                  <span className="mt-2 w-1.5 h-1.5 bg-brand-oak/20 rounded-full flex-shrink-0" />
                  <span>{point}</span>
                </li>
              ))}
            </ul>

            {exp.tech && (
              <div className="flex flex-wrap gap-2">
                {exp.tech.map((tag) => (
                  <span key={tag} className="text-[10px] font-mono uppercase tracking-widest px-2.5 py-1 rounded-full bg-white/5 border border-white/10 text-brand-steel">
                    {tag}
                  </span>
                ))}
              </div>
            )}
          </motion.div>
        ))}
      </div>

      {/* Volunteer/Peer Mentor Section */}
      <section className="pt-12">
        <h3 className="text-2xl font-bold mb-8 flex items-center space-x-3">
          <Briefcase className="text-brand-copper" />
          <span>{locale === 'en' ? "Volunteer & Social Impact" : "志愿服务与社会影响力"}</span>
        </h3>
        <div className="grid md:grid-cols-2 gap-6">
          <div className="p-8 rounded-2xl bg-white/[0.02] border border-white/5">
            <h4 className="font-bold text-lg mb-1">Victoria Heart Hospital</h4>
            <p className="text-brand-copper text-sm mb-4">Ward Ambassador</p>
            <p className="text-brand-oak text-sm">Dec 2024 – Jul 2025 · Guiding patients and managing front-desk reception in a high-stakes clinical environment.</p>
          </div>
          <div className="p-8 rounded-2xl bg-white/[0.02] border border-white/5">
            <h4 className="font-bold text-lg mb-1">Monash University</h4>
            <p className="text-brand-copper text-sm mb-4">Peer Mentor</p>
            <p className="text-brand-oak text-sm">Jan 2025 – Jun 2025 · Academic guidance for new students and inclusive support for students with disabilities.</p>
          </div>
        </div>
      </section>
    </div>
  );
}

// app/pages/experience.vue
<script setup lang="ts">
const { t } = useI18n()

const jobs = [
  {
    company: 'Citi Group',
    role: 'Tech Analyst',
    period: 'Jul 2021 – Jun 2024',
    duration: '3 years',
    type: 'Full-time',
    highlights: [
      'END USER COMPUTING: Python-based risk mitigation automation — recognised as Best Practice at annual Citi Risk knowledge-sharing.',
      'TIME RECORD SYSTEM: Selenium + RESTful API automation — reduced project management effort by 80%.',
      'FRTB Program: Data warehouse with JDBC, Oracle, Spark.',
      'Database Migration: Sybase → Oracle migration lead.',
      'Credit Risk: Global team collaboration on Trade Sensitive Matching system.',
    ],
    tech: ['Java', 'Python', 'SQL', 'Oracle', 'Sybase', 'Spark', 'Git', 'Jenkins', 'TeamCity'],
  },
  {
    company: 'Memo Studio',
    role: 'Founder & Producer',
    period: '2025 – Present',
    duration: '',
    type: 'Independent',
    highlights: [
      'Founded and lead Memo Studio, an independent game studio of ~10 members (writers, artists, programmers) on a volunteer + deferred revenue-share model.',
      'Owns end-to-end production: greenlight decisions, milestone planning, cross-discipline coordination, asset pipeline, and release management.',
      'Currently shipping: 失眠俱乐部 (Insomnia Club) visual novel demo; Chaos Brawler in design phase.',
    ],
    tech: ["Ren'Py", 'Godot 4', 'Stable Diffusion', 'Project Management'],
  },
]

const volunteer = [
  {
    org: 'Victoria Heart Hospital',
    role: 'Ward Ambassador',
    period: 'Dec 2024 – Jul 2025',
    desc: 'Guided patients and managed front-desk reception.',
  },
  {
    org: 'Monash University',
    role: 'Peer Mentor & Disability Peer Mentor',
    period: 'Jan 2025 – Jun 2025',
    desc: 'Academic guidance for new students; inclusive support for students with disabilities.',
  },
]
</script>

<template>
  <main class="px-8 md:px-20 pt-36 pb-20 max-w-3xl mx-auto">
    <h1 class="text-4xl font-light text-parchment mb-16 fade-up delay-1">
      {{ t('experience.title') }}
    </h1>

    <div class="space-y-16">
      <article
        v-for="(job, i) in jobs"
        :key="job.company"
        class="fade-up"
        :class="`delay-${i + 2}`"
      >
        <div class="flex flex-col md:flex-row md:items-baseline md:justify-between gap-2 mb-5">
          <div>
            <h2 class="text-parchment text-xl font-light">{{ job.company }}</h2>
            <p class="text-copper text-sm mt-0.5">{{ job.role }}</p>
          </div>
          <div class="flex items-baseline gap-3 shrink-0">
            <span class="text-steel text-xs tracking-wide">{{ job.type }}</span>
            <span class="text-oak text-sm">{{ job.period }}</span>
          </div>
        </div>

        <ul class="space-y-2 mb-5">
          <li
            v-for="h in job.highlights"
            :key="h"
            class="text-oak text-sm leading-relaxed pl-4 relative before:absolute before:left-0 before:top-2.5 before:w-1 before:h-px before:bg-copper/50"
          >
            {{ h }}
          </li>
        </ul>

        <div class="flex flex-wrap gap-2">
          <span
            v-for="tag in job.tech"
            :key="tag"
            class="text-steel text-xs px-2.5 py-1 bg-steel/10"
          >
            {{ tag }}
          </span>
        </div>

        <div class="mt-8 divider" />
      </article>
    </div>

    <!-- Volunteer -->
    <section class="mt-16 fade-up delay-4">
      <h2 class="text-xs text-steel tracking-[0.2em] uppercase mb-8">Volunteer</h2>
      <div class="space-y-8">
        <div
          v-for="v in volunteer"
          :key="v.org"
        >
          <div class="flex flex-col md:flex-row md:items-baseline md:justify-between gap-1 mb-2">
            <div>
              <p class="text-parchment">{{ v.org }}</p>
              <p class="text-copper text-sm">{{ v.role }}</p>
            </div>
            <span class="text-oak text-sm shrink-0">{{ v.period }}</span>
          </div>
          <p class="text-oak text-sm">{{ v.desc }}</p>
        </div>
      </div>
    </section>
  </main>
</template>
