// app/pages/about.vue
<script setup lang="ts">
const { t } = useI18n()
const researchOpen = ref(false)

const education = [
  {
    degree: 'Master of Information Technology',
    institution: 'Monash University',
    grade: 'HD Average',
    period: '2024–2026',
  },
  {
    degree: 'Bachelor of Computer Science',
    institution: 'University of Bristol',
    grade: '2:1',
    period: '2018–2021',
  },
]

const languages = [
  { lang: 'English', level: 'Superior', cert: 'PTE 79' },
  { lang: 'Mandarin', level: 'Native', cert: '—' },
  { lang: 'Japanese', level: 'Conversational', cert: '—' },
]

const skills = [
  { category: 'Languages', items: 'Java · Python · C/C++ · SQL · TypeScript · Go · Bash · R' },
  { category: 'Frontend', items: 'Vue.js 3 · Nuxt · HTML/CSS · Tailwind' },
  { category: 'Backend', items: 'Firebase · AWS Lambda · Node.js · REST API' },
  { category: 'Cloud', items: 'AWS (EC2 · Lambda · S3 · DynamoDB · Cognito · SNS) · Firebase' },
  { category: 'Tools', items: 'Git · Docker · Jenkins · JIRA · Selenium' },
  { category: 'ML / AI', items: 'TFLite · Stable Diffusion · Gemini API · LLM integration' },
  { category: 'Game Dev', items: 'Ren\'Py · Godot 4' },
  { category: 'Research', items: 'Multi-agent systems · LLM serving & scheduling · Cloud-edge computing · Batch inference optimisation' },
]
</script>

<template>
  <main class="px-8 md:px-20 pt-36 pb-20 max-w-3xl mx-auto">
    <h1 class="text-4xl font-light text-parchment mb-16 fade-up delay-1">
      {{ t('about.title') }}
    </h1>

    <!-- Education -->
    <section class="mb-16 fade-up delay-2">
      <h2 class="text-xs text-steel tracking-[0.2em] uppercase mb-6">
        {{ t('about.education') }}
      </h2>
      <div class="space-y-6">
        <div
          v-for="edu in education"
          :key="edu.institution"
          class="flex flex-col md:flex-row md:items-baseline md:justify-between gap-1 md:gap-4 pb-6 divider"
        >
          <div>
            <p class="text-parchment">{{ edu.degree }}</p>
            <p class="text-oak text-sm">{{ edu.institution }}</p>
          </div>
          <div class="flex items-baseline gap-4 shrink-0">
            <span class="text-steel text-sm">{{ edu.grade }}</span>
            <span class="text-oak text-sm">{{ edu.period }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- Research -->
    <section class="mb-16 fade-up delay-3">
      <h2 class="text-xs text-steel tracking-[0.2em] uppercase mb-6">
        {{ t('about.research') }}
      </h2>
      <div class="border border-oak/20 p-6">
        <p class="text-parchment mb-1 italic">
          Efficient Routing of Inference Requests across LLM Instances in Cloud-Edge Computing
        </p>
        <p class="text-steel text-sm mb-4">Supervisor: Dr. Mohammad Goudarzi · Monash University</p>

        <button
          class="text-copper text-sm hover:text-copper-dark transition-colors duration-200 flex items-center gap-2"
          @click="researchOpen = !researchOpen"
        >
          {{ researchOpen ? t('about.research_collapse') : t('about.research_expand') }}
          <span class="text-xs">{{ researchOpen ? '↑' : '↓' }}</span>
        </button>

        <Transition name="expand">
          <div v-if="researchOpen" class="mt-5 space-y-3 text-oak text-sm leading-relaxed">
            <p>
              <span class="text-parchment">Core problem:</span>
              How to intelligently dispatch a batch of heterogeneous LLM inference requests across multiple model instances distributed across cloud and edge nodes, minimising latency and cost while respecting SLA constraints.
            </p>
            <p>
              <span class="text-parchment">Approach:</span>
              Memetic Algorithm (MA) — evolutionary optimisation hybridised with local search, applied to the batch routing decision problem across heterogeneous LLM instances on cloud and edge nodes.
            </p>
            <p>
              <span class="text-parchment">Key topics:</span>
              Batch inference scheduling · LLM serving systems (vLLM-style) · Metaheuristic optimisation · Cloud-edge offloading · Throughput/latency trade-offs
            </p>
          </div>
        </Transition>
      </div>
    </section>

    <!-- Certifications -->
    <section class="mb-16 fade-up delay-3">
      <h2 class="text-xs text-steel tracking-[0.2em] uppercase mb-6">
        {{ t('about.certifications') }}
      </h2>
      <p class="text-parchment">AWS Solutions Architect – Associate</p>
    </section>

    <!-- Languages -->
    <section class="mb-16 fade-up delay-4">
      <h2 class="text-xs text-steel tracking-[0.2em] uppercase mb-6">
        {{ t('about.languages') }}
      </h2>
      <div class="space-y-3">
        <div
          v-for="l in languages"
          :key="l.lang"
          class="flex items-baseline justify-between pb-3 divider"
        >
          <span class="text-parchment">{{ l.lang }}</span>
          <div class="flex gap-6">
            <span class="text-oak text-sm">{{ l.level }}</span>
            <span class="text-steel text-sm">{{ l.cert }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- Skills -->
    <section class="fade-up delay-5">
      <h2 class="text-xs text-steel tracking-[0.2em] uppercase mb-6">
        {{ t('about.skills') }}
      </h2>
      <div class="space-y-4">
        <div
          v-for="s in skills"
          :key="s.category"
          class="flex flex-col md:flex-row gap-2 md:gap-8 pb-4 divider"
        >
          <span class="text-steel text-sm shrink-0 w-28">{{ s.category }}</span>
          <span class="text-oak text-sm">{{ s.items }}</span>
        </div>
      </div>
    </section>
  </main>
</template>

<style scoped>
.expand-enter-active,
.expand-leave-active {
  transition: opacity 0.3s ease;
}
.expand-enter-from,
.expand-leave-to {
  opacity: 0;
}
</style>

// src/pages/About.tsx
import { motion } from 'motion/react';
import { useI18n } from '../lib/i18n';
import { BookOpen, Award, Code2, Languages, GraduationCap } from 'lucide-react';

export default function About() {
  const { t, locale } = useI18n();

  const skills = [
    { category: { en: "Languages", zh: "编程语言" }, items: "Java, Python, C/C++, SQL, TypeScript, Go, Bash, R" },
    { category: { en: "Frontend", zh: "前端" }, items: "Vue.js 3, Nuxt, HTML/CSS, Tailwind" },
    { category: { en: "Backend", zh: "后端" }, items: "Firebase, AWS Lambda, Node.js, REST API" },
    { category: { en: "Cloud", zh: "云平台" }, items: "AWS (EC2, Lambda, S3, DynamoDB, Cognito, SNS), Firebase" },
    { category: { en: "Tools", zh: "工具" }, items: "Git, Docker, Jenkins, JIRA, Selenium" },
    { category: { en: "ML/AI", zh: "机器学习/AI" }, items: "TFLite, Stable Diffusion, Gemini API, LLM integration" },
    { category: { en: "Game Dev", zh: "游戏开发" }, items: "Ren'Py, Godot 4" },
  ];

  return (
    <div className="space-y-24">
      <section className="max-w-3xl">
        <h2 className="text-4xl font-bold mb-8">{t('about_title')}</h2>
        <p className="text-brand-oak text-lg leading-relaxed">
          {locale === 'en' 
            ? "I bridge the gap between technical precision and creative expression. From optimizing LLM inference at the cloud-edge to crafting interactive narratives, my work centers on efficiency, scalability, and human connection."
            : "我致力于在技术实现与创意表达之间搭建桥梁。从优化云边协同的LLM推理到构建深度叙事，我的工作核心围绕着效率、可扩展性和人际连接展开。"}
        </p>
      </section>

      {/* Education & Research */}
      <div className="grid md:grid-cols-2 gap-12">
        <section>
          <div className="flex items-center space-x-3 mb-6">
            <GraduationCap className="text-brand-copper" />
            <h3 className="text-xl font-bold">{locale === 'en' ? "Education" : "教育背景"}</h3>
          </div>
          <div className="space-y-8">
            <div className="border-l-2 border-brand-copper/30 pl-6 py-2">
              <h4 className="font-bold text-lg">Master of Information Technology</h4>
              <p className="text-brand-oak">Monash University · HD Average</p>
              <p className="text-sm text-brand-oak/60">2024 – 2026</p>
            </div>
            <div className="border-l-2 border-brand-copper/30 pl-6 py-2">
              <h4 className="font-bold text-lg">Bachelor of Computer Science</h4>
              <p className="text-brand-oak">University of Bristol · 2:1</p>
              <p className="text-sm text-brand-oak/60">2018 – 2021</p>
            </div>
          </div>
        </section>

        <section className="bg-white/5 p-8 rounded-2xl border border-white/10">
          <div className="flex items-center space-x-3 mb-4">
            <BookOpen className="text-brand-copper" />
            <h3 className="text-xl font-bold">{locale === 'en' ? "Research Thesis" : "研究课题"}</h3>
          </div>
          <h4 className="text-brand-copper font-medium mb-2">Efficient Routing of Inference Requests across LLM Instances in Cloud-Edge Computing</h4>
          <p className="text-sm text-brand-oak/80 italic mb-4">Supervisor: Dr. Mohammad Goudarzi</p>
          <p className="text-sm text-brand-oak leading-relaxed">
            {locale === 'en' 
              ? "Exploring Memetic Algorithms (MA) for intelligent dispatch of heterogeneous LLM inference requests across cloud and edge nodes, minimizing latency and cost while respecting SLA constraints."
              : "探索使用模因算法（MA）在云和边缘节点之间智能调度异构LLM推理请求，在遵守SLA约束的同时，最大限度地降低延迟和成本。"}
          </p>
        </section>
      </div>

      {/* Skills */}
      <section>
        <div className="flex items-center space-x-3 mb-8">
          <Code2 className="text-brand-copper" />
          <h3 className="text-2xl font-bold">{locale === 'en' ? "Technical Arsenal" : "技术栈"}</h3>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {skills.map((skill, index) => (
            <div key={index} className="p-6 rounded-xl border border-white/5 bg-white/[0.02] hover:bg-white/[0.05] transition-colors">
              <h4 className="text-brand-copper text-sm font-mono uppercase tracking-widest mb-2">{skill.category[locale]}</h4>
              <p className="text-brand-oak text-sm leading-relaxed">{skill.items}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Languages & Certs */}
      <div className="grid md:grid-cols-2 gap-12">
        <section>
          <div className="flex items-center space-x-3 mb-6">
            <Languages className="text-brand-copper" />
            <h3 className="text-xl font-bold">{locale === 'en' ? "Languages" : "语言能力"}</h3>
          </div>
          <div className="space-y-4">
            <div className="flex justify-between items-center bg-white/5 p-4 rounded-lg">
              <span className="font-medium">English</span>
              <span className="text-brand-oak text-sm">Superior (PTE 79)</span>
            </div>
            <div className="flex justify-between items-center bg-white/5 p-4 rounded-lg">
              <span className="font-medium">{locale === 'en' ? "Mandarin" : "普通话"}</span>
              <span className="text-brand-oak text-sm">{locale === 'en' ? "Native" : "母语"}</span>
            </div>
            <div className="flex justify-between items-center bg-white/5 p-4 rounded-lg">
              <span className="font-medium">{locale === 'en' ? "Japanese" : "日语"}</span>
              <span className="text-brand-oak text-sm">{locale === 'en' ? "Conversational" : "进修中"}</span>
            </div>
          </div>
        </section>

        <section>
          <div className="flex items-center space-x-3 mb-6">
            <Award className="text-brand-copper" />
            <h3 className="text-xl font-bold">{locale === 'en' ? "Certifications" : "证书资质"}</h3>
          </div>
          <div className="bg-white/5 p-6 rounded-xl border border-white/10 flex items-center space-x-4">
            <div className="w-12 h-12 bg-white/10 rounded-lg flex items-center justify-center">
              <Award className="text-brand-copper" size={24} />
            </div>
            <div>
              <h4 className="font-bold">AWS Solutions Architect – Associate</h4>
              <p className="text-brand-oak text-sm">Amazon Web Services</p>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
